#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
visualization.py — Plot HELIOS results (cross sections & near-fields).

This script loads outputs produced under sim_res/<sim>/ by run_sie.py and
renders either:
  (a) scattering/absorption/extinction cross sections vs. wavelength from *.csc,
  (b) near-field distributions from SIENanoPP outputs (.ein/.esc/.hin/.hsc)
      as 2D plane heat-maps or 3D colored scatter plots, and
  (c) 1D field cuts along a line within a plane (mode: 1d).

───────────────────────────────────────────────────────────────────────────────
Inputs & layout (relative to repository root)
───────────────────────────────────────────────────────────────────────────────
sim_res/<sim>/
  ├─ out/
  │   ├─ csc/                    # cross-section triplets per job
  │   └─ fields/
  │       ├─ <points_name>/      # preferred location for field files of a points set
  │       └─ sim<i>_inc_<j>.*    # fallback search if the subfolder is missing
  ├─ points/                     # .pos files with XYZ sample points (one per line)
  └─ lambdalist.txt              # optional map: job.<i> -> λ[nm] (auto-built if missing)

Points files are plain "x y z" text with no header. Field files are parsed
into complex vectors per line; flexible formats are recognized.

───────────────────────────────────────────────────────────────────────────────
Capabilities
───────────────────────────────────────────────────────────────────────────────
- Cross sections: read .csc, associate each curve with wavelength [nm] from
  lambdalist.txt or by parsing job.N.xml when needed; plot SCS/ACS/EXT.
- Near-fields: load E/H field files, choose quantity (|E|, Re(E_x), etc.),
  infer the plane (xz/xy/yz) from the point set, and render either:
  - 2D heat-map (pcolormesh) on rectilinear grids generated by make-points, or
  - 3D scatter fallback for arbitrary point clouds.
- 1D line cuts: select points along a geometric line defined by AXIS=VALUE
  (e.g., x=0) and plot scalar field vs. the remaining varying axis. The
  line must lie within the sampled plane (but the function will robustly infer
  the plotted axis even if the plane is not explicitly specified).

───────────────────────────────────────────────────────────────────────────────
CLI synopsis (selected)
───────────────────────────────────────────────────────────────────────────────
Cross sections:
  --plot-csc               Plot cross sections from *.csc
  --csc {scs,acs,ext}...   Which cross-section(s) to show
  --lambda-file FILE       Optional custom lambdalist (label λ_nm)

Near-fields:
  --points PATH|NAME            Points file or a name under sim_res/<sim>/points/
  --field {e,h}                 Field family to load
  --mode {2d,3d,1d}             Plot as 2D heat-map, 3D scatter, or 1D line cut
  --quantity {total,x,y,z}      Quantity to plot
  --function {intensity, magnitude, real, imag, phase} 
                                How to process the selected quantity
  --hlines z1 z2 ...            Horizontal guide lines (e.g., layer interfaces)

1D line cuts:
  --line AXIS=VALUE          Geometric selector for the line (e.g., x=0, y=50, z=150)
  --tol  FLOAT               Tolerance for selecting points on the line (default: 1e-6)
  Notes:
    - The line axis must belong to the detected plane (e.g., x or z for an xz plane).
    - The value is snapped to the nearest grid coordinate with a warning if far.
    - Samples are sorted by the varying in-plane coordinate before plotting.

Lambda selection:
  -L, --lambda NM          Choose the sim index closest to the requested λ[nm]

───────────────────────────────────────────────────────────────────────────────
Notes & conventions
───────────────────────────────────────────────────────────────────────────────
- Field file discovery prioritizes out/fields/<points_name>/, then falls back
  to out/fields/ and a recursive search.
- If lambdalist.txt is absent, a best-effort wavelength is inferred by parsing
  job XMLs and/or numeric stems like 'sim3'.
- 2D plots assume the points lie on a rectilinear grid (as produced by
  run_sie.py make-points). Irregular clouds are visualized with the 3D mode.
- 1D plots reuse the same grid and operate on precomputed field values only.

"""

import argparse
import re
import pathlib
from pathlib import Path
from typing import List, Tuple, Optional, Dict

import numpy as np
import matplotlib.pyplot as plt

# try Mie library
try:
    import miepython as mie
    _HAS_MIEPY = True
except Exception:
    _HAS_MIEPY = False

# -------------------------
# Paths
# -------------------------
def sim_root_dir(sim: str, root: Path) -> Path: return (root / sim).resolve()
def sim_out_dir(sim: str, root: Path) -> Path: return (sim_root_dir(sim, root) / "out").resolve()
def sim_fields_dir(sim: str, root: Path) -> Path: return (sim_out_dir(sim, root) / "fields").resolve()
def sim_points_dir(sim: str, root: Path) -> Path: return (sim_root_dir(sim, root) / "points").resolve()
def sim_jobs_dir(sim: str, root: Path) -> Path: return (sim_root_dir(sim, root) / "jobs").resolve()

def list_files_with_ext(folder: Path, ext: str) -> List[Path]:
    return sorted([p for p in folder.glob(f"*.{ext}") if p.is_file()])

# -------------------------
# Points IO
# -------------------------
def resolve_points_path(points_arg: str, sim: str, root: Path) -> Tuple[Path, str]:
    """
    Resolve a points file from multiple user-friendly inputs:
    1) absolute/relative path,
    2) sim_res/<sim>/points/<name>,
    3) any match under sim_res/<sim>/**.
    Returns (absolute_path, points_name) where points_name tags the subfolder in fields/.
    """
    p = Path(points_arg)
    if p.exists():
        return p.resolve(), (p.parent.name if p.parent.name not in ("points", "") else p.stem)

    pd = sim_points_dir(sim, root)
    for cand in [pd / points_arg, sim_root_dir(sim, root) / points_arg]:
        if cand.exists():
            return cand.resolve(), (cand.parent.name if cand.parent != pd else cand.stem)

    matches = list(pd.rglob(points_arg))
    if matches:
        m = matches[0].resolve()
        return m, (m.parent.name if m.parent != pd else m.stem)

    raise FileNotFoundError(f"Points file not found: {points_arg} (searched {pd}/**/)")

def load_points(points_file: Path) -> np.ndarray:
    """
    Load plain XYZ points, ignoring comments and forgiving separators (, ; spaces).
    Raises if no valid triplets are found.
    """
    pts: List[List[float]] = []
    with open(points_file, "r") as f:
        for line in f:
            s = line.strip()
            if not s or s[0] in "#%/":
                continue
            s = s.replace(",", " ").replace(";", " ")
            parts = s.split()
            if len(parts) < 3: continue
            try:
                x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
            except ValueError:
                continue
            pts.append([x, y, z])
    if not pts:
        raise ValueError(f"No points parsed from {points_file}")
    return np.asarray(pts, dtype=float)

# -------------------------
# Field IO
# -------------------------
def _parse_complex_triplet_line(line: str) -> Optional[List[complex]]:
    """
    Parse one line into three complex components (Ex,Ey,Ez or Hx,Hy,Hz).
    Accepts:
    - '(Re,Im) (Re,Im) (Re,Im)'     <- canonical HELIOS output
    - 'Re Im  Re Im  Re Im'         <- bare numeric pairs
    - Python-like tokens with 'i/j' <- tolerant fallback
    Returns list[complex] length 3, or None for blanks/comments.
    """
    s = line.strip()
    if not s or s[0] in "#%/":
        return None

    # 1) Fast path: explicit (Re,Im) tuples
    m_all = re.findall(r"\(\s*([-+]?[\d\.Ee+-]+)\s*,\s*([-+]?[\d\.Ee+-]+)\s*\)", s)
    if len(m_all) >= 3:
        trip = [complex(float(a), float(b)) for (a, b) in m_all[:3]]
        return trip

    # 2) Six bare numbers: Re Im Re Im Re Im
    nums = re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", s)
    if len(nums) >= 6:
        a1, b1, a2, b2, a3, b3 = [float(v) for v in nums[:6]]
        return [complex(a1, b1), complex(a2, b2), complex(a3, b3)]

    # 3) Fallback: try python complex after normalizing 'i'->'j'
    s2 = s.replace("i", "j")
    toks = s2.replace(";", " ").split()
    row: List[complex] = []
    for t in toks:
        t = t.replace("*1j", "j")
        try:
            row.append(complex(t))
        except Exception:
            # also accept a lone real
            try:
                row.append(complex(float(t), 0.0))
            except Exception:
                pass
    return row[:3] if len(row) >= 3 else None

def _load_vec_field(file_path: Path, fill_policy: str = "nan") -> np.ndarray:
    """
    Read a vector field file and return an (N,3) complex array.
    Keeps row count: unparsable/placeholder lines are filled, not skipped.
    fill_policy: "nan" -> (nan+1j*nan), "big" -> (1e10+1j*1e10)
    """
    def _filler():
        if fill_policy.lower() == "big":
            v = complex(1e10, 1e10)
            return [v, v, v]
        # default: NaNs
        v = complex(np.nan, np.nan)
        return [v, v, v]

    data: List[List[complex]] = []
    with open(file_path, "r") as f:
        for raw in f:
            s = raw.strip()
            # treat an explicit "None" (or variants) as a data row that needs filling
            if s and s.lower().startswith("none"):
                data.append(_filler())
                continue

            parsed = _parse_complex_triplet_line(raw)
            if parsed is None:
                # blank/comment -> preserve alignment by filling (instead of skipping)
                data.append(_filler())
            else:
                # ensure triplet length
                if len(parsed) < 3:
                    data.append(_filler())
                else:
                    data.append(parsed[:3])

    if not data:
        raise ValueError(f"No vector data parsed from {file_path}")
    return np.asarray(data, dtype=np.complex128)

def _find_field_files(fields_dir: Path, ext: str, points_name: Optional[str],
                      sim_idx: Optional[int] = None,
                      subjob_idx: Optional[int] = None) -> List[Path]:
    """
    Return candidate field files for extension 'ext' with priority:
    1) fields/<points_name>/sim{idx}_*.ext (if points_name set),
    2) fields/sim{idx}_*.ext,
    3) fields/**/sim{idx}_*.ext (recursive fallback).
    If sim_idx is None, use '*.ext' at each step.

    If subjob_idx is provided, keep only files whose name matches:
        sim<digits>_<token>_<subjob>.<ext>   (e.g., sim1_inc_2.ein)
    """
    patt = f"*.{ext}" if sim_idx is None else f"sim{sim_idx}_*.{ext}"

    def _filter_subjob(files: List[Path]) -> List[Path]:
        if subjob_idx is None:
            return files
        kept = []
        for p in files:
            m = re.search(r"^sim\d+_[A-Za-z]+_(\d+)\." + re.escape(ext) + r"$", p.name)
            if m and int(m.group(1)) == int(subjob_idx):
                kept.append(p)
        return kept

    files: List[Path] = []
    if points_name:
        p1 = fields_dir / points_name
        if p1.exists():
            files = sorted([p for p in p1.glob(patt) if p.is_file()])
            files = _filter_subjob(files)
            if files:
                return files

    files = sorted([p for p in fields_dir.glob(patt) if p.is_file()])
    files = _filter_subjob(files)
    if files:
        return files

    files = sorted([p for p in fields_dir.rglob(patt) if p.is_file()])
    files = _filter_subjob(files)
    return files

def _load_field(fields_dir: Path, what: str, points_name: Optional[str],
                sim_idx: Optional[int] = None, subjob_idx: Optional[int] = None,
                fill_policy: str = "nan") -> np.ndarray:
    """Load a field file with extension 'what'."""
    files = _find_field_files(fields_dir, what, points_name, sim_idx=sim_idx, subjob_idx=subjob_idx)
    if not files:
        raise FileNotFoundError(f"No '.{what}' files in {fields_dir} (searched recursively)")
    arrs = [_load_vec_field(p, fill_policy=fill_policy) for p in files]
    return np.vstack(arrs)

def _unique_sorted(values: np.ndarray, tol: float = 1e-9) -> np.ndarray:
    """Unique 1D with tolerance (for z-levels)."""
    vs = np.array(values, dtype=float)
    vs.sort()
    out = []
    for v in vs:
        if not out or abs(v - out[-1]) > tol:
            out.append(v)
    return np.asarray(out, dtype=float)

def _parse_job_for_label(jobs_dir, label_str):
    """
    Resolve the propagation vector from the job XML that generated a label like:
      'out/sim<i>_inc_<j>'
    Extract <i> (job index) and <j> (subjob index). For subjob==1, read from the
    top-level <job><planewave>. For subjob>1, locate the <subjob> whose <label>
    exactly matches label_str and read its <planewave>. Polarization is ignored
    (it is provided as input elsewhere).
    Returns kvec.
    """
    m = re.search(r"sim(\d+)_inc_(\d+)", label_str)
    if not m:
        raise FileNotFoundError(f"Unrecognized label format: {label_str}")
    job_idx = int(m.group(1)); sub_idx = int(m.group(2))
    job_xml = Path(jobs_dir) / f"job.{job_idx}.xml"
    if not job_xml.exists():
        raise FileNotFoundError(f"Missing job XML: {job_xml}")
    txt = job_xml.read_text(errors="ignore")
    # pick the block to parse
    if sub_idx == 1:
        block_m = re.search(r"<\s*job\b[\s\S]*?</\s*job\s*>", txt, re.IGNORECASE)
        block = block_m.group(0) if block_m else txt
    else:
        block = None
        for sm in re.finditer(r"<\s*subjob\b[\s\S]*?</\s*subjob\s*>", txt, re.IGNORECASE):
            sblk = sm.group(0)
            lm = re.search(r"<\s*label\s*>\s*([^<]+)\s*</\s*label\s*>", sblk, re.IGNORECASE)
            if lm and lm.group(1).strip() == label_str:
                block = sblk; break
        if block is None:
            # fallback by index order if labels are absent/mismatched
            allsubs = list(re.finditer(r"<\s*subjob\b[\s\S]*?</\s*subjob\s*>", txt, re.IGNORECASE))
            sib = max(0, sub_idx - 2)
            block = allsubs[sib].group(0) if sib < len(allsubs) else txt
    # parse propagation within chosen block
    km = re.search(r"<\s*propagation[^>]*>([^<]+)<", block, re.IGNORECASE)
    if km:
        nums = [float(t) for t in re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", km.group(1))]
        kvec = np.array((nums + [0, 0, 1])[:3], dtype=float)
    else:
        kvec = np.array([0.0, 0.0, 1.0], dtype=float)  # default +z
    return kvec

def _select_quantity(field, comp, mode="magnitude"):
    """
    Select quantity (total vector or x/y/z scalar) and apply operation (intensity, magnitude, real, etc).
    field: (N, 3) complex array
    """
    comp = comp.lower()
    mode = mode.lower()

    # 1. Identify raw data: Vector (total) or Scalar (component)
    if comp in ["total"]:
        raw = field
        is_vector = True
    else:
        idx = {"x": 0, "y": 1, "z": 2}[comp]
        raw = field[:, idx]
        is_vector = False

    # 2. Apply Operation
    if mode == "intensity":
        # |v|^2 for scalar, |vx|^2+|vy|^2+|vz|^2 for vector
        if is_vector:
            return np.sum(np.abs(raw)**2, axis=1)
        return np.abs(raw)**2

    elif mode == "real":
        # Only valid for scalar components. For vector, fallback to magnitude.
        if is_vector:
            return np.sqrt(np.sum(np.abs(raw)**2, axis=1))
        return np.real(raw)

    elif mode == "imag":
        if is_vector:
            return np.sqrt(np.sum(np.abs(raw)**2, axis=1))
        return np.imag(raw)

    elif mode == "phase":
        if is_vector:
            # Phase undefined for total vector magnitude; return 0 or fallback
            return np.zeros(len(raw)) 
        return np.angle(raw)

    else: 
        # "magnitude", "abs", or default
        if is_vector:
            return np.sqrt(np.sum(np.abs(raw)**2, axis=1))
        return np.abs(raw)

# -------------------------
# Near-field plot
# -------------------------
def _detect_plane_axes(pts: np.ndarray) -> Tuple[str, str, int]:
    """
    Decide which 2 coordinates vary most and therefore form the plotting plane.
    Returns (axis1, axis2, fixed_index) where fixed_index is the column that is constant-ish.
    """
    uniq_counts = [len(np.unique(pts[:,i])) for i in range(3)]
    # pick two largest counts; if tie, prefer xz then xy then yz
    order = np.argsort(uniq_counts)[::-1]
    a, b, c = order[0], order[1], order[2]
    names = ["x","y","z"]
    # map to user-friendly default preference
    if set([a,b]) == set([0,2]): return ("x","z", 1)  # xz plane, fix y
    if set([a,b]) == set([0,1]): return ("x","y", 2)  # xy plane, fix z
    if set([a,b]) == set([1,2]): return ("y","z", 0)  # yz plane, fix x
    return (names[a], names[b], c)

def _grid_from_points(pts: np.ndarray, values: np.ndarray,
                      axes: Optional[str] = None) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Given points (N,3) and scalar values (N,), return (X, Y, V) suitable for pcolormesh.
    If axes is provided ('xz','xy','yz'), use that; else auto-detect.
    Assumes data lie on a rectilinear grid (as in typical plane-point files).
    """
    if axes is None:
        a1, a2, fixed = _detect_plane_axes(pts)
        axes = a1 + a2
    axes = axes.lower()
    idx = {"x":0,"y":1,"z":2}
    i = idx[axes[0]]; j = idx[axes[1]]

    xs = np.unique(pts[:, i])
    ys = np.unique(pts[:, j])
    # Build map from (x,y) -> value
    xi = {v:k for k,v in enumerate(xs)}
    yj = {v:k for k,v in enumerate(ys)}
    V = np.full((len(ys), len(xs)), np.nan, dtype=float)
    for p, val in zip(pts, values):
        V[yj[p[j]], xi[p[i]]] = val

    # Create X,Y mesh (as 2D arrays) from unique vectors
    X, Y = np.meshgrid(xs, ys)
    return X, Y, V

def _plane_grid_info(points, tol=None):
    """
    Infer the plane (two varying axes), the fixed axis, and per-axis unique coords.
    Returns:
        vary_axes: tuple(int,int)       # e.g., (0,2) for xz
        fixed_axis: int                 # e.g., 1 for y (xz plane)
        coords: dict[int, np.ndarray]   # unique sorted coords for each axis
        steps: dict[int, float]         # median step for each varying axis
    Assumes a rectilinear plane grid like the one created by make-points.
    """
    pts = np.asarray(points)
    uniq = [np.unique(pts[:, i]) for i in range(3)]
    lens = [len(u) for u in uniq]
    vary_axes = tuple(sorted(np.argsort(lens)[-2:]))
    fixed_axis = ({0,1,2} - set(vary_axes)).pop()
    coords = {i: np.sort(np.unique(pts[:, i])) for i in range(3)}
    def median_step(arr):
        if len(arr) < 2: return 0.0
        dif = np.diff(arr); dif = dif[np.abs(dif) > 0]
        return float(np.median(dif)) if dif.size else 0.0
    steps = {i: median_step(coords[i]) for i in vary_axes}
    return vary_axes, fixed_axis, coords, steps


def _parse_line_spec(spec: str):
    """Parse 'x=0', 'y=50', 'z=150' -> (axis_index, value)."""
    s = spec.strip().lower().replace(" ", "")
    if "=" not in s:
        raise ValueError("line spec must be AXIS=VALUE, e.g., x=0")
    ax, val = s.split("=", 1)
    idx_map = {"x": 0, "y": 1, "z": 2}
    if ax not in idx_map:
        raise ValueError("line axis must be one of x,y,z")
    try:
        v = float(val)
    except Exception:
        raise ValueError(f"invalid numeric value in --line: {val}")
    return idx_map[ax], v


def _extract_line_series(points, scalar, line_axis, line_value, tol=1e-6):
    """
    Grid-aware 1D extraction for plane data created by make-points.
    - Verifies the line axis belongs to the plane's varying axes.
    - Snaps the requested value to the nearest grid coordinate along that axis.
    - Selects all points on that snapped line and returns (x_sorted, y_sorted, x_label).
    """
    pts = np.asarray(points); val = np.asarray(scalar)
    if pts.shape[0] != val.shape[0]:
        raise ValueError("points and scalar must have the same number of rows")

    vary_axes, fixed_axis, coords, steps = _plane_grid_info(pts)
    if line_axis not in vary_axes:
        plane = "".join("xyz"[a] for a in vary_axes)
        raise ValueError(
            f"--line must fix one of the plane axes ({plane}). "
            f"Axis '{'xyz'[line_axis]}' appears fixed ({'xyz'[fixed_axis]}-normal plane)."
        )

    grid = coords[line_axis]
    if grid.size == 0:
        raise ValueError("could not infer grid along requested axis")

    idx = int(np.argmin(np.abs(grid - line_value)))
    snapped = float(grid[idx])

    step = steps.get(line_axis, 0.0)
    if step > 0 and abs(snapped - line_value) > 0.51 * step:
        print(f"[warn] --line { 'xyz'[line_axis] }={line_value} far from grid; snapped to {snapped} (step≈{step})")

    atol = max(tol, step * 0.25 if step > 0 else tol)
    mask = np.isclose(pts[:, line_axis], snapped, atol=atol)
    if not np.any(mask):
        raise ValueError("no points found on the requested line after snapping (adjust --tol)")

    subp = pts[mask]; subv = val[mask]
    other_axis = vary_axes[1] if vary_axes[0] == line_axis else vary_axes[0]
    x = subp[:, other_axis]
    order = np.argsort(x)
    x_sorted = x[order]
    y_sorted = subv[order]
    if np.iscomplexobj(y_sorted):
        y_sorted = np.abs(y_sorted)
    x_label = "xyz"[other_axis]
    return x_sorted, y_sorted, x_label

def plot_fields(points: np.ndarray, color_vals: np.ndarray, label: str,
                title: str = "", save: Optional[Path] = None, show: bool = True):
    """
    3D heat-map of the field on the detected (or hinted) plane using pcolormesh.
    """
    fig = plt.figure(figsize=(15.5, 6.5))
    ax = fig.add_subplot(111, projection='3d')
    sc = ax.scatter(points[:,0], points[:,1], points[:,2], c=color_vals, s=12)
    cb = fig.colorbar(sc, ax=ax, shrink=0.7, pad=0.05); cb.set_label("Values")
    ax.set_xlabel("x [nm]"); ax.set_ylabel("y [nm]"); ax.set_zlabel("z [nm]")
    ax.set_title(title)
    if save:
        plt.savefig(save, bbox_inches="tight", dpi=300); print(f"[saved] {save}")
    if show: plt.show()
    plt.close(fig)

def plot_fields_2d(points: np.ndarray,
                   color_vals: np.ndarray,
                   axes_hint: Optional[str],
                   hlines: Optional[List[float]],
                   title: str = "",
                   save: Optional[Path] = None,
                   show: bool = True):
    """
    2D heat-map of the field on the detected (or hinted) plane using pcolormesh.
    - 'hlines' overlays horizontal guides (e.g., layer interfaces).
    """
    # grid in native coordinates (assumed nm)
    X, Y, V = _grid_from_points(points, color_vals, axes=axes_hint)

    fig, ax = plt.subplots(figsize=(4.6, 4.2))
    h = ax.pcolormesh(X, Y, V, shading="auto")
    cb = fig.colorbar(h, ax=ax)
    cb.set_label("Values")

    # axis labels
    _, fixed_axis, _, _ = _plane_grid_info(points)
    if fixed_axis == 0:
        ax.set_xlabel(f"y [nm]")
        ax.set_ylabel(f"z [nm]")
    elif fixed_axis == 1:
        ax.set_xlabel(f"x [nm]")
        ax.set_ylabel(f"z [nm]")
    else:
        ax.set_xlabel(f"x [nm]")
        ax.set_ylabel(f"y [nm]")
    ax.set_aspect("equal")

    # optional horizontal lines
    if hlines:
        for z in hlines:
            ax.axhline(z, color="white", linewidth=1.2)

    ax.set_title(title)
    fig.tight_layout()
    if save:
        plt.savefig(save, bbox_inches="tight", dpi=300)
        print(f"[saved] {save}")
    if show:
        plt.show()
    plt.close(fig)

def plot_fields_1d(ax, points, vec_field, which="total", func_mode="abs",
                   line_spec=None, tol=1e-6, hlines: Optional[List[float]] = None,
                   title: str = "", x_label: str = "Values", log_scale: bool = False):
    """1D line cut: select points on AXIS=VALUE and plot scalar vs. varying coord.
    - which: 'total', 'x', 'y', 'z'
    - func_mode: 'intensity', 'magnitude', 'real', 'imag', 'phase'
    - line_spec: 'x=0' | 'y=...' | 'z=...'
    - tol: geometric tolerance in nm
    - 'hlines' overlays horizontal guides (e.g., layer interfaces).
    - title: plot title
    - x_label: label for the horizontal axis (Values)
    """
    if not line_spec:
        raise ValueError("--line AXIS=VALUE is required for 1d mode")
    ax_idx, ax_val = _parse_line_spec(line_spec)

    # Select quantity and function mode
    scalar = _select_quantity(vec_field, which, mode=func_mode)

    # Build series (grid-aware). x_native is the varying spatial coord along the line.
    x_native, y_scalar, coord_label = _extract_line_series(points, scalar, ax_idx, ax_val, tol=tol)

    # Values on x-axis (optionally log10)
    if log_scale:
        base = np.abs(y_scalar)
        x_field = np.log10(np.maximum(base, 1e-30))
    else:
        x_field = np.abs(y_scalar) if np.iscomplexobj(y_scalar) else y_scalar

    # overlay horizontal lines
    if hlines:
        for v in hlines:
            ax.axhline(v, linestyle="--", linewidth=1.0, color="0.3", zorder=3)

    ax.plot(x_field, x_native)
    ax.set_xlabel(x_label)
    ax.set_ylabel(f"{coord_label} [nm]")
    ax.grid(True, alpha=0.3)
    ax.set_title(f"1D cut at {'xyz'[ax_idx]}={ax_val} ({title})")

# -------------------------
# Cross sections & λ
# -------------------------
HC_EV_NM = 1239.841984
C_M_S = 299792458.0
TWOPI = 2*np.pi

def read_csc_values(csc_file: Path) -> Tuple[float, float, float]:
    """Parse first non-comment line of a .csc file into (SCS, ACS, EXT)."""
    with open(csc_file, "r") as f:
        for line in f:
            s = line.strip()
            if not s or s[0] in "#%/": continue
            s = s.replace(",", " ").replace(";", " ")
            vals: List[float] = []
            for tok in s.split():
                try: vals.append(float(tok))
                except Exception: pass
            if len(vals) >= 3: return vals[0], vals[1], vals[2]
    raise ValueError(f"Could not parse values from {csc_file}")

def _extract_number_unit_pairs(text: str) -> List[Tuple[float, str]]:
    """Utility for extracting (value, unit) pairs from text [nm, µm, m, eV, Hz..]."""
    pairs: List[Tuple[float, str]] = []
    for m in re.finditer(r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*(nm|um|µm|micron|microns|m|hz|khz|mhz|ghz|thz|ev)\b", text, re.IGNORECASE):
        val = float(m.group(1)); unit = m.group(2).lower(); pairs.append((val, unit))
    return pairs

def _to_nm_from_value_unit(val: float, unit: str) -> Optional[float]:
    """Convert a (value, unit) pair to wavelength in nm (returns None if unknown)."""
    unit = unit.lower()
    if unit == "nm": return val
    if unit in ("um","µm","micron","microns"): return val*1e3
    if unit == "m": return val*1e9
    if unit == "ev": return HC_EV_NM/val if val!=0 else None
    if unit in ("hz","khz","mhz","ghz","thz"):
        mul = {"hz":1.0,"khz":1e3,"mhz":1e6,"ghz":1e9,"thz":1e12}[unit]
        f = val*mul
        return (C_M_S/f)*1e9 if f!=0 else None
    return None

def _parse_lambda_nm_from_xml(xml_path: Path) -> Optional[float]:
    """
    Heuristically extract wavelength [nm] from a job XML by checking tags, attributes,
    and free text; also accepts frequency (ω or f) with unit conversion.
    """
    txt = xml_path.read_text(errors="ignore")
    m = re.search(r"<\s*(wavelength|lambda|vacuum_wavelength|lambda0)\b[^>]*unit\s*=\s*\"([^\"]+)\"[^>]*>([^<]+)<", txt, re.IGNORECASE)
    if m:
        unit = m.group(2).strip().lower()
        nums = re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", m.group(3))
        if nums:
            val = float(nums[0]); lam = _to_nm_from_value_unit(val, unit)
            if lam is not None: return lam
    m = re.search(r"<\s*(wavelength|lambda|vacuum_wavelength|lambda0)\b[^>]*>([^<]+)<", txt, re.IGNORECASE)
    if m:
        blob = m.group(2); pairs = _extract_number_unit_pairs(blob)
        if pairs:
            lam = _to_nm_from_value_unit(*pairs[0]); 
            if lam is not None: return lam
        nums = re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", blob)
        if nums: return float(nums[0])
    m = re.search(r"<\s*(frequency|freq|f|omega|w)\b[^>]*unit\s*=\s*\"([^\"]+)\"[^>]*>([^<]+)<", txt, re.IGNORECASE)
    if m:
        unit = m.group(2).strip().lower(); nums = re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", m.group(3))
        if nums:
            val = float(nums[0])
            if m.group(1).lower() in ("omega","w"): val = val/TWOPI; unit="hz"
            lam = _to_nm_from_value_unit(val, unit)
            if lam is not None: return lam
    for key in ("wavelength","lambda","vacuum_wavelength","lambda0","frequency","freq","f","omega","w"):
        m = re.search(rf"{key}\s*=\s*\"([^\"]+)\"", txt, re.IGNORECASE)
        if m:
            for val, unit in _extract_number_unit_pairs(m.group(1)):
                lam = _to_nm_from_value_unit(val, unit)
                if lam is not None: return lam
    for val, unit in _extract_number_unit_pairs(txt):
        lam = _to_nm_from_value_unit(val, unit)
        if lam is not None: return lam
    return None

def ensure_lambdalist(sim: str, root: Path, lambda_file: Optional[Path] = None) -> Dict[str, float]:
    """
    Ensure sim/lambdalist.txt exists; if absent, derive λ per job.N.xml and write it.
    Returns dict label -> λ_nm.
    """
    simdir = sim_root_dir(sim, root)
    lf = lambda_file if lambda_file else (simdir / "lambdalist.txt")
    if lf.exists():
        mapping: Dict[str,float] = {}
        with open(lf,"r") as f:
            for line in f:
                s=line.strip()
                if not s or s[0] in "#%/": continue
                parts=s.split()
                if len(parts)>=2:
                    try: mapping[parts[0]]=float(parts[1])
                    except: pass
        if mapping: return mapping
    jobs_dir = sim_jobs_dir(sim, root)
    if not jobs_dir.exists(): raise FileNotFoundError(f"Jobs dir not found: {jobs_dir}")
    xmls = sorted(jobs_dir.glob("*.xml"))
    if not xmls: raise FileNotFoundError(f"No job XMLs in {jobs_dir}")
    mapping: Dict[str,float] = {}
    for x in xmls:
        lam_nm = _parse_lambda_nm_from_xml(x)
        if lam_nm is not None: mapping[x.stem]=lam_nm
    if not mapping:
        placeholder = simdir / "lambdalist.txt"
        with open(placeholder,"w") as f:
            f.write("# Could not auto-extract wavelengths; fill as: <label> <wavelength_nm>\n")
            for x in xmls: f.write(f"{x.stem} 0\n")
        raise RuntimeError(f"Could not extract wavelengths. Edit {placeholder} and rerun.")
    with open(lf,"w") as f:
        f.write("# label  wavelength_nm\n")
        for k,v in mapping.items(): f.write(f"{k} {v:.9g}\n")
    print(f"[info] wrote {lf}")
    return mapping

def _best_label_match_by_index(stem: str, labels: List[str]) -> Optional[str]:
    """
    Prefer numeric index mapping: sim1_* -> job.1, job2_* -> job.2, *_<n> -> job.<n>, etc.
    """
    # extract first integer index
    m = re.search(r"(?:^|[^\d])(\d+)(?:[^\d]|$)", stem)
    if m:
        idx = m.group(1)
        # try exact 'job.idx'
        cand = f"job.{idx}"
        if cand in labels: return cand
        # try any label ending with idx or having .idx
        for L in labels:
            if L.endswith(f".{idx}") or re.search(rf"(?:^|[^\d]){idx}(?:[^\d]|$)", L):
                return L
    # substring heuristic fallback
    for L in labels:
        if L in stem or stem in L: return L
    return None

def _dedupe_or_fallback(lams: np.ndarray, stems: List[str], labels: List[str], lambda_map: Dict[str,float]) -> np.ndarray:
    """If duplicate λ's dominate but lengths match, align by sorted order as a fallback."""
    if len(np.unique(lams)) < len(lams) and len(labels) == len(lams):
        sorted_stems = sorted(stems)
        sorted_labels = sorted(labels)
        remap = {st: la for st, la in zip(sorted_stems, sorted_labels)}
        lam2 = np.array([lambda_map.get(remap.get(st, ""), np.nan) for st in stems], dtype=float)
        return lam2
    return lams


# ------------------------- material helpers (Mie) -------------------------
def _parse_scalar_spec(spec: str):
    s = spec.strip().lower()
    if s.startswith("eps="):
        a,b = s.split("=",1)[1].replace(" ","").split(",")
        eps = complex(float(a), float(b))
        n = np.sqrt(eps+0j)
        return lambda lam_nm: np.full_like(lam_nm, n, dtype=np.complex128)
    if s.startswith("nk="):
        a,b = s.split("=",1)[1].replace(" ","").split(",")
        n = complex(float(a), float(b))  # n + i k
        return lambda lam_nm: np.full_like(lam_nm, n, dtype=np.complex128)
    return None

def _try_material_file(path: Path):
    if path.exists() and path.is_file():
        return path
    for ext in (".txt",".dat",".csv"):
        p = path.with_suffix(ext)
        if p.exists():
            return p
    return None

def _load_material_table(fp: Path):
    """Load table with columns:
       (λ[nm], n, k)  or  (λ[nm], Re(ε), Im(ε))  or  constant: (n, k) / (Re(ε), Im(ε)).
       Returns (lam_nm or None, n_complex or eps_complex)."""
    rows = []
    with open(fp, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            s = line.strip()
            if not s or s[0] in "#%;/":
                continue
            toks = [t for t in re.split(r"[,\s;]+", s) if t]
            try:
                vals = list(map(float, toks))
            except Exception:
                continue
            if len(vals) >= 2:
                rows.append(vals)
    if not rows:
        raise RuntimeError(f"No numeric rows parsed from {fp}")
    arr = np.asarray(rows, dtype=float)
    if arr.shape[1] == 2:
        # constant across λ
        v1, v2 = arr[0,0], arr[0,1]
        return None, (v1 + 1j*v2, None)  # ambiguous; caller decides nk vs. eps
    # assume first column is λ[nm]
    lam = arr[:,0]
    v1, v2 = arr[:,1], arr[:,2]
    return lam, (v1 + 1j*v2, None)  # ambiguous; caller decides nk vs. eps

def _material_n_vs_lambda(spec: str, matroot: str, lam_nm: np.ndarray,
                          use_spline: bool = False) -> np.ndarray:
    """Return complex refractive index n(λ) for λ[nm]."""
    # 1) direct scalar spec
    f = _parse_scalar_spec(spec)
    if f:
        return f(lam_nm)
    # 2) file / bare name
    s = spec.strip()
    root = Path(matroot)
    if s.startswith("@"):
        fp = _try_material_file(Path(s[1:]))
        if not fp:
            fp = _try_material_file((root / s[1:]))
    else:
        fp = _try_material_file(root / s)
    if not fp:
        raise FileNotFoundError(f"Material not found: {spec} (searched under {matroot})")
    lam_tab, pair = _load_material_table(fp)
    # Heuristic: if file name contains 'nk', treat as (n,k); if contains 'eps', treat as ε
    is_nk = ("nk" in fp.stem.lower())
    if lam_tab is None:
        # constant across λ
        val = pair[0]
        if is_nk:
            n_const = val
        else:
            n_const = np.sqrt(val+0j)
        return np.full_like(lam_nm, n_const, dtype=np.complex128)
    else:
        v = pair[0]  # complex series (either n+ik or complex eps)
        if is_nk:
            n_ser = v
        else:
            n_ser = np.sqrt(v+0j)
        # interpolate real and imaginary parts on λ-grid
        if use_spline:
            try:
                from scipy.interpolate import interp1d  # optional dependency
                fr = interp1d(lam_tab, np.real(n_ser), kind="cubic",
                              bounds_error=False, fill_value="extrapolate")
                fi = interp1d(lam_tab, np.imag(n_ser), kind="cubic",
                              bounds_error=False, fill_value="extrapolate")
                nr = fr(lam_nm)
                ni = fi(lam_nm)
            except Exception:
                # graceful fallback to linear interpolation
                nr = np.interp(lam_nm, lam_tab, np.real(n_ser))
                ni = np.interp(lam_nm, lam_tab, np.imag(n_ser))
        else:
            nr = np.interp(lam_nm, lam_tab, np.real(n_ser))
            ni = np.interp(lam_nm, lam_tab, np.imag(n_ser))
        return nr + 1j*ni

def plot_csc_line_with_lambda(out_dir: Path,
                              lambda_map: Dict[str, float],
                              series: List[str],
                              save: Optional[Path],
                              show: bool,
                              mie_opts: Optional[dict] = None,
                              subjob: Optional[int] = None):
    """Plot selected cross-section series vs. wavelength after labeling each .csc by λ."""
    files = list_files_with_ext(out_dir, "csc")
    if not files:
        raise FileNotFoundError(f"No .csc files in {out_dir}")

    if subjob is not None:
        filt = [f for f in files if f"inc_{subjob}" in f.stem]
        # Only enforce the filter if we actually found matches
        if filt:
            files = filt

    labels = list(lambda_map.keys())
    stems: List[str] = []
    lam_list: List[float] = []
    sca_list: List[float] = []
    abs_list: List[float] = []
    ext_list: List[float] = []

    for f in files:
        s, a, e = read_csc_values(f)
        lab = _best_label_match_by_index(f.stem, labels)
        lam = lambda_map.get(lab, np.nan)
        stems.append(f.stem); lam_list.append(lam); sca_list.append(s); abs_list.append(a); ext_list.append(e)

    lam = np.array(lam_list, dtype=float)
    lam = _dedupe_or_fallback(lam, stems, labels, lambda_map)

    mask = ~np.isnan(lam)
    lam = lam[mask]; sca = np.array(sca_list)[mask]; abs_ = np.array(abs_list)[mask]; ext = np.array(ext_list)[mask]

    order = np.argsort(lam)
    lam, sca, abs_, ext = lam[order], sca[order], abs_[order], ext[order]

    fig, ax = plt.subplots(figsize=(8.5, 4.8))
    sel_map: Dict[str, Tuple[np.ndarray, str]] = {
        "scs": (sca,  "SIE scs"),
        "acs": (abs_, "SIE acs"),
        "ext": (ext,  "SIE ext"),
    }

    # normalize selection once (used by both simulation & Mie)
    series_set = {s.lower() for s in series} if series else {"scs", "acs", "ext"}
    
    # Standard CSC curves (only selected)
    for key in sorted(series_set):
        y, label = sel_map[key.lower()]
        ax.plot(lam, y, marker="o", label=label)

    if mie_opts and _HAS_MIEPY:
        R = float(mie_opts["radius_nm"])    # radius in nm
        mat = mie_opts["mat"]
        bg = mie_opts.get("bg", "eps=1,0")
        root = mie_opts["matroot"]
        use_spline = bool(mie_opts.get("spline", False))

        # Material refractive indices
        n_part = _material_n_vs_lambda(mat, root, lam, use_spline=use_spline)
        n_bg   = _material_n_vs_lambda(bg,  root, lam, use_spline=use_spline)

        # Relative refractive index and size parameter
        m = n_part / n_bg
        x = 2.0 * np.pi * R * np.abs(n_bg) / lam   # dimensionless

        geo = np.pi * R**2                         # nm^2
        Csca, Cext = [], []

        for mi, xi, lami, nbi in zip(m, x, lam, n_bg):
            try:
                Qext, Qsca, *_ = mie.efficiencies_mx(mi, xi)
            except Exception:
                Qsca = Qext = np.nan

            Csca.append(Qsca * geo)
            Cext.append(Qext * geo)

        Csca = np.array(Csca)
        Cext = np.array(Cext)
        Cabs = Cext - Csca
        if "acs" in series_set:
            ax.plot(lam, Cabs, "--", label=f"Mie acs")
        if "ext" in series_set:
            ax.plot(lam, Cext, "--", label=f"Mie ext")
        if "scs" in series_set:
            ax.plot(lam, Csca, "--", label=f"Mie scs")

    elif mie_opts and not _HAS_MIEPY:
        print("[warn] miepython not installed; skipping Mie overlay.")   

    ax.set_xlabel("Wavelength [nm]")
    ax.set_ylabel(r"Cross section [$\mathrm{nm^2}$]")

    if len(series) == 1:
        key = series[0].lower()
        if key == "scs":
            title = "Scattering Cross Section vs. Wavelength"
        elif key == "acs":
            title = "Absorption Cross Section vs. Wavelength"
        elif key == "ext":
            title = "Extinction Cross Section vs. Wavelength"
        else:
            title = "Cross Section vs. Wavelength"
    else:
        title = "Cross Sections vs. Wavelength"
    ax.set_title(title)

    ax.legend()
    fig.tight_layout()
    if save: plt.savefig(save, bbox_inches="tight", dpi=300); print(f"[saved] {save}")
    if show: plt.show()
    plt.close(fig)

def _read_lambdalist_simple(lf: Path) -> dict:
    """
    Accepts either 'label wavelength' or 'wavelength' per line.
    Returns dict: label_or_index -> wavelength_nm
    """
    m = {}
    with open(lf, "r") as f:
        for i, line in enumerate(f, 1):
            s = line.strip()
            if not s or s[0] in "#%/":
                continue
            parts = s.split()
            if len(parts) == 1:
                # single column: wavelength only; index by line number
                m[str(i)] = float(parts[0])
            else:
                m[parts[0]] = float(parts[1])
    if not m:
        raise RuntimeError(f"{lf} exists but no wavelengths parsed.")
    return m

def _choose_sim_index_for_lambda(lmap: dict, target_nm: float) -> int:
    """
    From a dict like {'job.1': 532, 'job.2': 650, '3': 780, ...},
    return the integer sim index whose λ is best (exact first, else nearest).
    """
    # Build index->λ by extracting trailing integer from keys; fallback to enumerate
    idx_to_wl = {}
    for k, wl in lmap.items():
        m = re.search(r"(\d+)$", k)
        if m:
            idx_to_wl[int(m.group(1))] = wl
    if not idx_to_wl:
        # fallback: assign 1..N in file order
        idx_to_wl = {i+1: wl for i, wl in enumerate(lmap.values())}

    # exact match first
    for idx, wl in idx_to_wl.items():
        if abs(wl - target_nm) < 1e-9:
            return idx
    # nearest
    return min(idx_to_wl.keys(), key=lambda i: abs(idx_to_wl[i] - target_nm))

# -------------------------
# CLI
# -------------------------
def main():
    ap = argparse.ArgumentParser(description="Visualize simulation results.")
    ap.add_argument("sim", nargs="+", help="Simulation name(s) (subfolder(s) of --root). For --plot-csc you may pass multiple.")
    ap.add_argument("--root", default="sim_res", help="Results root (default: sim_res)")
    ap.add_argument("--subjob", type=int, default=1,
                    help="Subjob index (the trailing number in files like sim1_inc_2.*). Default: 1")
    
    # Reflectance & Transmittance vs. λ
    ap.add_argument("--plot-rt", action="store_true",
                    help="Plot reflectance & transmittance vs. wavelength from field files on two z-planes")
    ap.add_argument("--rt-prop", choices=["auto", "+1", "-1"], default="auto",
                    help="Propagation direction along z: '+1' for +z, '-1' for -z, 'auto' for infer from job XML.")

    # Cross-section plotting: pulls λ either from lambdalist or job XMLs (auto).
    ap.add_argument("--plot-csc", action="store_true", help="Plot cross sections from *.csc vs. wavelength [nm]")
    ap.add_argument("--csc", action="append", choices=["scs", "acs", "ext"],
                    help="Which series to show (repeatable). Default: all three")
    ap.add_argument("--lambda-file", type=str, default=None,
                    help="Optional custom lambdalist file (format: 'label wavelength_nm')")

    # Mie overlay options
    ap.add_argument("--mie-radius", type=float, default=None,
                    help="Sphere radius in nm for Mie comparison overlay")
    ap.add_argument("--mie-material", type=str, default=None,
                    help="Material of the sphere. Accepts eps=Re,Im | nk=n,k | @file | name (looked up under --materials-root).")
    ap.add_argument("--mie-background", type=str, default="eps=1,0",
                    help="Background material (same grammar as --mie-material). Default: vacuum.")
    ap.add_argument("--materials-root", type=str, default="materials",
                    help="Folder to search material files when using @file or bare names (default: materials)")
    ap.add_argument("--mie-spline", action="store_true",
                    help="Use spline interpolation for tabulated Mie material data (if SciPy is available)")

    # Near-fields
    ap.add_argument("--points", type=str, default=None, help="Points filename (searched under sim/points/**/)")
    ap.add_argument("--field",  type=str, choices=["e","h"], help="Field family: E or H")
    ap.add_argument("--lambda", "-L", dest="lambda_nm", type=float, default=None, 
                    help="Wavelength in nm to plot the field for (uses lambdalist.txt to pick the matching simN_* files)." )
    ap.add_argument("--part",   type=str, choices=["inc","sc","tot"], help="Incident / Scattered / Total")
    ap.add_argument("--quantity", type=str, default="total", choices=["total","x","y","z"],
                    help="Quantity to extract (total=vector, x/y/z=scalar). Default: total")
    ap.add_argument("--function", choices=["intensity","magnitude","abs","real","imag","phase"], default="magnitude",
                    help="Operation to apply (intensity=|v|^2, magnitude=|v|). Default: magnitude")
    ap.add_argument("--mode", type=str, default="2d", choices=["3d","2d","1d"],
                    help="Plot mode for near-fields: 2d heat-map, 3d scatter, or 1d line cut")                  
    ap.add_argument("--line", type=str, default=None,
                    help="1D line selector: AXIS=VALUE (e.g., x=0, y=50, z=150)")
    ap.add_argument("--tol", type=float, default=1e-6,
                    help="Tolerance for selecting points on the line [nm]")
    ap.add_argument("--hlines", type=str, default=None,
                    help="Comma-separated z-values [nm] to draw horizontal lines on 2D plot, e.g. 0,50,100")
    ap.add_argument("--log", action="store_true",
                    help="Apply log10 scaling to the field magnitude before plotting (Fields mode only)")    


    # Output
    ap.add_argument("--save", type=str, default=None, help="Save figure to this path")
    ap.add_argument("--show", action="store_true", help="Show interactive window")

    args = ap.parse_args()
    root = Path(args.root)

    # In non-CSC modes, we require exactly one simulation.
    if not args.plot_csc and len(args.sim) != 1:
        raise SystemExit("Only --plot-csc supports multiple simulations. Provide exactly one <sim> for Fields and R/T/A.")

    # Cross-sections vs. λ (supports multiple sims plotted together)
    if args.plot_csc:
        series = args.csc if args.csc else ["scs","acs","ext"]
        series_set = {s.lower() for s in series} if series else {"scs","acs","ext"}

        mie_opts = None
        if args.mie_radius and args.mie_material:
            mie_opts = {
                "radius_nm": args.mie_radius,
                "mat": args.mie_material,
                "bg": args.mie_background,
                "matroot": str((Path.cwd() / args.materials_root).resolve()),
                "spline": bool(args.mie_spline),
            }

        fig, ax = plt.subplots(figsize=(8.5, 4.8))

        for simname in args.sim:
            out_dir = sim_out_dir(simname, root)
            lambda_file = Path(args.lambda_file).resolve() if args.lambda_file else None
            lam_map = ensure_lambdalist(simname, root, lambda_file=lambda_file)
            csc_dir = out_dir / "csc"

            # --- load this sim's CSC data (replicates logic from plot_csc_line_with_lambda) ---
            files = list_files_with_ext(csc_dir, "csc")
            if not files:
                print(f"[warn] No .csc files in {csc_dir}; skipping {simname}")
                continue

            if args.subjob is not None:
                filt = [f for f in files if f"inc_{args.subjob}" in f.stem]
                if filt:
                    files = filt

            labels = list(lam_map.keys())
            stems, lam_list, sca_list, abs_list, ext_list = [], [], [], [], []
            for f in files:
                s, a, e = read_csc_values(f)
                lab = _best_label_match_by_index(f.stem, labels)
                lam = lam_map.get(lab, np.nan)
                stems.append(f.stem); lam_list.append(lam)
                sca_list.append(s); abs_list.append(a); ext_list.append(e)

            lam = np.array(lam_list, dtype=float)
            lam = _dedupe_or_fallback(lam, stems, labels, lam_map)

            mask = ~np.isnan(lam)
            lam = lam[mask]
            sca = np.array(sca_list)[mask]
            abs_ = np.array(abs_list)[mask]
            ext  = np.array(ext_list)[mask]

            order = np.argsort(lam)
            lam, sca, abs_, ext = lam[order], sca[order], abs_[order], ext[order]

            sel_map = {
                "scs": (sca,  "scs"),
                "acs": (abs_, "acs"),
                "ext": (ext,  "ext"),
            }
            for key in sorted(series_set):
                y, short = sel_map[key]
                ax.plot(lam, y, marker="o", label=f"{simname} — {short}")

        # Optional Mie overlay once (based on the λ grid from plotted data)
        # We reuse the first Line2D's x-data as the λ grid (if any).
        if mie_opts and _HAS_MIEPY and ax.lines:
            lam_grid = ax.lines[0].get_xdata()
            R = float(mie_opts["radius_nm"])
            mat = mie_opts["mat"]
            bg  = mie_opts.get("bg", "eps=1,0")
            rootm = mie_opts["matroot"]
            use_spline = bool(mie_opts.get("spline", False))

            n_part = _material_n_vs_lambda(mat, rootm, lam_grid, use_spline=use_spline)
            n_bg   = _material_n_vs_lambda(bg,  rootm, lam_grid, use_spline=use_spline)
            mrel = n_part / n_bg
            x = 2.0 * np.pi * R * np.abs(n_bg) / lam_grid
            geo = np.pi * R**2
            Csca, Cext = [], []
            for mi, xi in zip(mrel, x):
                try:
                    Qext, Qsca, *_ = mie.efficiencies_mx(mi, xi)
                except Exception:
                    Qsca = Qext = np.nan
                Csca.append(Qsca * geo)
                Cext.append(Qext * geo)
            Csca = np.array(Csca)
            Cext = np.array(Cext)
            Cabs = Cext - Csca
            if "acs" in series_set: ax.plot(lam_grid, Cabs, "--", label="Mie acs")
            if "ext" in series_set: ax.plot(lam_grid, Cext, "--", label="Mie ext")
            if "scs" in series_set: ax.plot(lam_grid, Csca, "--", label="Mie scs")
        elif mie_opts and not _HAS_MIEPY:
            print("[warn] miepython not installed; skipping Mie overlay.")

        ax.set_xlabel("Wavelength [nm]")
        ax.set_ylabel(r"Cross section [$\mathrm{nm^2}$]")
        ax.set_title("Cross Sections vs. Wavelength")
        ax.grid(True, alpha=0.3)
        ax.legend()
        fig.tight_layout()
        if args.save:
            fig.savefig(Path(args.save), bbox_inches="tight", dpi=300)
            print(f"[saved] {args.save}")
        if args.show:
            plt.show()
        plt.close(fig)

    # Reflectance and Transmittance vs. λ
    if args.plot_rt:
        simname = args.sim[0]
        fields_dir = sim_fields_dir(simname, root)
        jobs_dir   = sim_jobs_dir(simname, root)
        if not args.points:
            raise SystemExit("--points is required for --plot-rt")
        pts_path, pts_name = resolve_points_path(args.points, simname, root)
        pts = load_points(pts_path)
        if pts.shape[1] != 3:
            raise SystemExit("Points file must have 3 columns (x y z)")
        zvals = _unique_sorted(pts[:, 2])
        if len(zvals) < 2:
            raise SystemExit("R/T/A requires at least two distinct z-planes in the points file")

        # collect available sim indices for this subjob
        def _sim_idx_of(p: Path) -> int:
            m = re.search(r"sim(\d+)_inc_", p.stem)
            return int(m.group(1)) if m else -1
        ext_list = []
        for ext in ("ein", "esc", "hin", "hsc"):
            ext_list += list((fields_dir / (pts_name or "")).rglob(f"sim*_inc_{args.subjob}.{ext}"))
            if not ext_list:
                ext_list += list(fields_dir.rglob(f"sim*_inc_{args.subjob}.{ext}"))
        sim_indices = sorted({i for i in (_sim_idx_of(p) for p in ext_list) if i > 0})
        if not sim_indices:
            raise SystemExit(f"No field files sim*_inc_{args.subjob}.* found under {fields_dir}")

        # λ map: prefer lambdalist file
        lambda_file = sim_root_dir(simname, root) / "lambdalist.txt"
        ensure_lambdalist(simname, root, lambda_file=lambda_file)
        lam_map_any = _read_lambdalist_simple(lambda_file)
        # build idx->λ
        idx_to_nm = {}
        for k, wl in lam_map_any.items():
            m = re.search(r"(\d+)$", k)
            if m: idx_to_nm[int(m.group(1))] = wl
        if not idx_to_nm:
            idx_to_nm = {i+1: wl for i, wl in enumerate(lam_map_any.values())}
        lambdas_nm = [idx_to_nm.get(i, float(i)) for i in sim_indices]

        # propagation direction: manual override via --rt-prop, or auto from job XML
        if args.rt_prop == "+1":
            kz = 1.0
        elif args.rt_prop == "-1":
            kz = -1.0
        else:
            # auto mode: infer sign from job XML for label "out/sim<i>_inc_<subjob>"
            label0 = f"out/sim{sim_indices[0]}_inc_{args.subjob}"
            kvec   = _parse_job_for_label(jobs_dir, label0)
            kz = float(np.sign(kvec[2])) if kvec.size >= 3 else 1.0

        # choose R/T/A planes based on sign(kz)*sign(z) < 0 for reflection
        z_ref = None
        for zplane in zvals:
            if kz * np.sign(zplane if zplane != 0 else 1e-12) < 0:
                z_ref = zplane; break
        if z_ref is None:
            z_ref = zvals.min() if kz > 0 else zvals.max()
        z_trn = zvals.max() if z_ref == zvals.min() else zvals.min()

        R, T = [], []

        # helper to load one field file for a given sim index
        def _one(i: int, ext: str) -> np.ndarray:
            base = (fields_dir / (pts_name or ""))
            cand = list(base.rglob(f"sim{i}_inc_{args.subjob}.{ext}"))
            if not cand:
                cand = list(fields_dir.rglob(f"sim{i}_inc_{args.subjob}.{ext}"))
            if not cand:
                raise FileNotFoundError(f"Missing sim{i}_inc_{args.subjob}.{ext}")
            return _load_vec_field(cand[0])

        for i in sim_indices:
            E_in = _one(i, "ein"); H_in = _one(i, "hin")
            E_sc = _one(i, "esc"); H_sc = _one(i, "hsc")
            n = min(len(pts), len(E_in), len(E_sc), len(H_in), len(H_sc))
            P = pts[:n]

            # Masks for planes
            mask_ref = np.isclose(P[:, 2], z_ref, rtol=0, atol=1e-9)
            mask_trn = np.isclose(P[:, 2], z_trn, rtol=0, atol=1e-9)

            # Full-field Poynting vectors at all points
            S_in_all  = 0.5 * np.real(np.cross(E_in[:n], np.conj(H_in[:n])))
            S_ref_all = 0.5 * np.real(np.cross(E_sc[:n], np.conj(H_sc[:n])))
            S_trn_all = 0.5 * np.real(np.cross(E_in[:n] + E_sc[:n], np.conj(H_in[:n] + H_sc[:n])))

            # Sign convention: +sgn*z is the nominal forward direction
            sgn = 1.0 if kz > 0 else -1.0; eps = 1e-30

            # Reflection plane: ratio per point, then mean
            Sin_z   =  S_in_all[:, 2][mask_ref]  * sgn          # forward (positive) incident
            Sin_z   = np.where(np.abs(Sin_z) > eps, np.abs(Sin_z), np.nan)
            Sref_z  = -S_ref_all[:, 2][mask_ref] * sgn          # reflected flows opposite
            r_ratio = Sref_z / Sin_z                            # per-point ratio
            r_ratio = np.clip(r_ratio, 0.0, None)               # avoid tiny negative due to noise
            R.append(np.nanmean(r_ratio) if np.any(np.isfinite(r_ratio)) else np.nan)

            # Transmission plane: ratio per point, then mean
            Strn_z  = S_trn_all[:, 2][mask_trn] * sgn           # transmitted flows forward
            t_ratio = Strn_z / Sin_z                            # per-point ratio
            t_ratio = np.clip(t_ratio, 0.0, None)               # avoid tiny negative due to noise
            T.append(np.nanmean(t_ratio) if np.any(np.isfinite(t_ratio)) else np.nan)

        tot = np.ones_like(R)
        fig, ax = plt.subplots(figsize=(7.0, 5.0))
        ax.plot(lambdas_nm, R, "green", lw=2.0, marker="o", label="R")
        ax.plot(lambdas_nm, T, "blue",  lw=2.0, marker="o", label="T")
        ax.set_xlabel("Wavelength [nm]")
        ax.set_ylabel("Power coefficients")
        ax.grid(True, alpha=0.3)
        ax.legend(loc="best")
        dir_tag = fr", $k_z > 0$" if kz > 0 else fr", $k_z < 0$"
        ax.set_title(fr"$R$ & $T$ - (subjob {args.subjob}{dir_tag})")
        if args.save:
            fig.savefig(Path(args.save), dpi=300, bbox_inches="tight")
            print(f"[saved] {args.save}")
        if args.show:
            plt.show()
        plt.close(fig)
        return

    # pick a specific sim index from the lambdalist if --lambda/-L was given
    sim_idx_for_lambda = None
    if args.lambda_nm is not None:
        simname = args.sim[0]
        # ensure lambdalist exists even for fields-only runs
        lambda_file = Path(args.lambda_file).resolve() if args.lambda_file else (sim_root_dir(simname, root) / "lambdalist.txt")
        lam_map_labels = ensure_lambdalist(simname, root, lambda_file=lambda_file)
        # read back robustly (accepts 1 or 2 columns)
        lam_map_any = _read_lambdalist_simple(lambda_file)
        sim_idx_for_lambda = _choose_sim_index_for_lambda(lam_map_any, args.lambda_nm)
        chosen_nm = None
        # try to get the actual λ we chose, for a friendly print
        try:
            # rebuild idx->λ to fetch value
            m2 = {}
            for k, wl in lam_map_any.items():
                m = re.search(r"(\d+)$", k)
                if m:
                    m2[int(m.group(1))] = wl
            if not m2:
                m2 = {i+1: wl for i, wl in enumerate(lam_map_any.values())}
            chosen_nm = m2.get(sim_idx_for_lambda, None)
        except Exception:
            pass
        if chosen_nm is not None:
            print(f"[info] lambda request = {args.lambda_nm:.3f} nm -> using sim{sim_idx_for_lambda} (lambda={chosen_nm:.3f} nm)")
        else:
            print(f"[info] lambda request = {args.lambda_nm:.3f} nm -> using sim{sim_idx_for_lambda}")

    # Near-field mode requires a points file and existing out/fields/ data.
    if args.field and args.part:
        simname = args.sim[0]
        fields_dir = sim_fields_dir(simname, root)
        if not fields_dir.exists():
            raise SystemExit(f"Fields directory not found: {fields_dir}")
        if not args.points:
            raise SystemExit("--points is required for near-field plotting")

        pts_path, points_name = resolve_points_path(args.points, simname, root)
        pts = load_points(pts_path)

        # build base names
        if args.field == "e":
            base_inc, base_sc = "ein", "esc"
        else:
            base_inc, base_sc = "hin", "hsc"

        sub_idx = int(args.subjob) if args.subjob is not None else None

        if args.part == "inc":
            field = _load_field(fields_dir, base_inc, points_name, 
                                sim_idx=sim_idx_for_lambda, subjob_idx=sub_idx, fill_policy="nan")
        elif args.part == "sc":
            field = _load_field(fields_dir, base_sc, points_name, 
                                sim_idx=sim_idx_for_lambda, subjob_idx=sub_idx, fill_policy="nan")
        else:  # tot
            finc = _load_field(fields_dir, base_inc, points_name, 
                               sim_idx=sim_idx_for_lambda, subjob_idx=sub_idx, fill_policy="nan")
            fsc  = _load_field(fields_dir, base_sc, points_name, 
                               sim_idx=sim_idx_for_lambda, subjob_idx=sub_idx, fill_policy="nan")
            if finc.shape != fsc.shape:
                raise ValueError("Shape mismatch between incident and scattered fields")
            field = finc + fsc

        n = min(len(pts), len(field))
        if n == 0:
            raise RuntimeError("No overlapping rows between points and field arrays.")
        if n != len(pts) or n != len(field):
            print(f"[warn] points = {len(pts)}, field rows = {len(field)} -> plotting first {n} rows.")

        color_vals = _select_quantity(field[:n], args.quantity, mode=args.function)
        # Optional log10 scaling for 2D/3D color values
        if args.log:
            # avoid log(0) and negative/complex issues
            color_vals = np.log10(np.maximum(np.abs(color_vals), 1e-30))        
        
        # Construct title based on selections
        sym = args.field.upper()
        sub = args.part
        
        if args.quantity == "total":
            # Vector notation
            base = fr"\mathbf{{{sym}}}_{{{sub}}}"
            if args.function == "intensity":
                title = fr"$|{base}|^2$"
            else:
                title = fr"$|{base}|$"
        else:
            # Scalar notation
            base = fr"{sym}_{{{sub},{args.quantity}}}"
            if args.function == "intensity":
                title = fr"$|{base}|^2$"
            elif args.function == "real":
                title = fr"$\Re({base})$"
            elif args.function == "imag":
                title = fr"$\Im({base})$"
            elif args.function == "phase":
                title = fr"$\angle {base}$"
            else:
                title = fr"$|{base}|$"
        
        if args.lambda_nm is not None and 'chosen_nm' in locals() and chosen_nm is not None:
            title += f" @ λ={chosen_nm:.2f} nm"

        if args.mode == "2d":
            # parse --hlines if provided
            hvals = None
            if args.hlines:
                try:
                    hvals = [float(v) for v in args.hlines.split(",") if v.strip() != ""]
                except Exception:
                    print("[warn] Failed to parse --hlines; ignoring.")
                    hvals = None

            # Auto-detect plane from the points set; keep axes_hint=None for auto mode.
            plot_fields_2d(
                pts[:n],
                color_vals,
                axes_hint=None,
                hlines=hvals,
                title=title + (" (log10)" if args.log else ""),
                save=(Path(args.save) if args.save else None) if not args.plot_csc else None,
                show=args.show,
            )

        elif args.mode == "1d":
            # 1D line cut along AXIS=VALUE inside the detected plane grid
            if not args.line:
                raise SystemExit("1d mode requires --line AXIS=VALUE (e.g., --line x=0)")

            # Optionally echo the detected plane (safe if helper is present; otherwise skip)
            try:
                vary_axes, _, _, _ = _plane_grid_info(pts[:n])
                print(f"[info] detected plane: {''.join('xyz'[a] for a in vary_axes)}")
            except Exception:
                pass

            fig, ax = plt.subplots(figsize=(7, 4))
            # Parse --hlines (values are in nm)
            hvals = None
            if args.hlines:
                try:
                    hvals = [float(v) for v in args.hlines.split(",") if v.strip() != ""]
                except Exception:
                    print("[warn] Failed to parse --hlines; ignoring.")
                    hvals = None

            title1d = f""
            # Construct title based on selections
            sym = args.field.upper()
            sub = args.part
            
            if args.quantity == "total":
                # Vector notation
                base = fr"\mathbf{{{sym}}}_{{{sub}}}"
                if args.function == "intensity":
                    title1d = fr"$|{base}|^2$"
                else:
                    title1d = fr"$|{base}|$"
            else:
                # Scalar notation
                base = fr"{sym}_{{{sub},{args.quantity}}}"
                if args.function == "intensity":
                    title1d = fr"$|{base}|^2$"
                elif args.function == "real":
                    title1d = fr"$\Re({base})$"
                elif args.function == "imag":
                    title1d = fr"$\Im({base})$"
                elif args.function == "phase":
                    title1d = fr"$\arg({base})$"
                else:
                    title1d = fr"$|{base}|$"
            if args.lambda_nm is not None and 'chosen_nm' in locals() and chosen_nm is not None:
                title1d += f" @ λ={chosen_nm:.3f} nm"

            # Use the vector field to let the helper pick the right quantity
            plot_fields_1d(
                ax,
                pts[:n],
                field[:n],
                which=args.quantity,      # "total","x","y","z"
                func_mode=args.function,  # "intensity", "magnitude", "real", "imag", "phase"
                line_spec=args.line,      # e.g., "x=0"
                tol=args.tol,             # selection tolerance
                hlines=hvals,             # optional horizontal lines
                title=title1d + (" (log10)" if args.log else ""),  # title
                log_scale=bool(args.log), # log scale flag
            )

            plt.tight_layout()
            if args.save and not args.plot_csc:
                outp = pathlib.Path(args.save)
                fig.savefig(outp, dpi=300, bbox_inches="tight")
            if args.show:
                plt.show()

        else:
            # 3D scatter
            label = f"|{args.field.upper()}{args.quantity}|"
            plot_fields(
                pts[:n],
                color_vals,
                label=label,
                title=title + (" (log10)" if args.log else ""),
                save=(Path(args.save) if args.save else None) if not args.plot_csc else None,
                show=args.show,
            )

    if (not args.plot_csc) and not (args.field and args.part):
        print("Nothing to do. Use --plot-csc and/or --field with --part and --points.")

if __name__ == "__main__":
    main()
